apiVersion: goopy.us/v1
kind: GameServer
metadata:
  name: sackbuoy-server
  namespace: games
spec:
  gameType: "minecraft-java"
  helmChart:
    repository: https://itzg.github.io/minecraft-server-charts
    name: minecraft
    version: 4.26.3
    valuesOverride: |-
      minecraftServer:
        eula: true
    timeout: 300

