apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s.io/no-provisioner  # This will be different based on your environment
reclaimPolicy: Delete
volumeBindingMode: Immediate
