apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gameservers.goopy.us
spec:
  group: goopy.us
  names:
    kind: GameServer
    plural: gameservers
    singular: gameserver
    shortNames:
      - gs
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
              properties:
                name:
                  type: string
                generateName:
                  type: string
            spec:
              type: object
              # Define your specific resource properties here
              properties:
                # Your custom fields go here
                gameType:
                  type: string

